FROM timbru31/java-node
LABEL maintainer "Mohammad-Ali A'râbi <mohammad-ali@aerabi.com>"

RUN apt-get update && apt-get install -y git wget
RUN wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.9/swagger-codegen-cli-2.4.9.jar -O /opt/swagger-codegen-cli.jar

