FROM timbru31/java-node
LABEL maintainer "Mohammad-Ali A'râbi <mohammad-ali@aerabi.com>"

RUN apt-get update && apt-get install -y git wget
RUN wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/3.0.0-rc1/swagger-codegen-cli-3.0.0-rc1.jar -O /opt/swagger-codegen-cli.jar

